VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Const1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Au As Boolean
Public Ful As Boolean
Public Re As Boolean
Public Plflag As Boolean
Public Lo As Boolean
Public top1 As Single
Public left1  As Single
Public PlCount As Integer
Public Plmode As Byte
Public RestVol As Long
Public SoundEff As Boolean
Public Min1 As Boolean
Public PrevSize As Integer
Public SetFocu As Boolean
Public Logopa As String
Public Stp As Long
Public Etp As Long
Public CDPath As String
Public FullScr As Byte
Public Logopa1 As String
Public Ct1 As Boolean
Public ct2 As Boolean
Public ct3 As Boolean
Public Minz As Boolean
Public Tis As Single
Public Lo1 As Integer
Public SoundEff1 As Boolean
Public SoundCount1 As Single
Public RateCount1 As Single
Public Left3D As Single
Public Right3D As Single
Public Swap As Boolean


